apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kuiper.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kuiper.labels" . | nindent 4 }}
data:
    {{- toYaml .Values.kuiperConfig | nindent 4 }}